style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: "git@git.omise.co:Pradit/spark-project-template.git"
options:
  tag_filter_pattern: "^v"
  commits:
     filters:
       Type:
         - feat
         - fix
         - perf
         - refactor
         - docs
         - chore
  commit_groups:
     title_maps:
       feat: Features
       fix: Bug Fixes
       perf: Performance Improvements
       refactor: Code Refactoring
       docs: Documentation
       chore: Miscellaneous
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
